micronaut:
  application:
    name: micronaut_problem_json_duplicate_fields
netty:
  default:
    allocator:
      max-order: 3
problem:
  enabled: true
  stack-trace: false  # Toggling this to true fixes this issue.
